import { Card } from "@/components/ui/card";
import type { ProjectAnalytics } from "@/lib/consumer-analytics";

const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const colors = { refund: "bg-[#007a6e]", waiting: "bg-[#e06c2e]", other: "bg-[#667085]" };

export function ProjectDemandChart({ rows }: { rows: ProjectAnalytics[] }) {
  const max = Math.max(...rows.map((row) => row.units), 1);
  const totalUnits = rows.reduce((total, row) => total + row.units, 0);
  const totalRefund = rows.reduce((total, row) => total + row.refund, 0);
  const totalWaiting = rows.reduce((total, row) => total + row.waiting, 0);
  return <Card className="p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-medium text-ink">Consumer units by project</h2><p className="mt-1 text-sm text-muted">Unit population with Tuntutan shown in high-contrast stacked columns.</p></div><p className="font-mono text-sm text-muted">{totalUnits} units</p></div><div className="mt-5 flex flex-wrap gap-4 font-mono text-[11px] text-muted"><Legend color={colors.refund} label={`Refund · ${totalRefund}`} /><Legend color={colors.waiting} label={`Waiting for development · ${totalWaiting}`} /><Legend color={colors.other} label="Not specified" /></div><div className="mt-7 overflow-x-auto"><div className="flex min-w-[680px] items-end gap-3 border-b border-hairline pb-2" style={{ height: 310 }}>{rows.map((row) => <div key={row.project} className="flex min-w-16 flex-1 flex-col justify-end self-stretch"><div className="mb-2 text-center font-mono text-xs text-ink">{row.units}</div><div className="flex h-60 flex-col justify-end overflow-hidden rounded-t-md bg-surface-soft"><VerticalSegment value={row.refund} max={max} color={colors.refund} /><VerticalSegment value={row.waiting} max={max} color={colors.waiting} /><VerticalSegment value={row.other} max={max} color={colors.other} /></div><div title={row.project} className="mt-2 line-clamp-2 min-h-8 text-center text-[11px] leading-tight text-muted">{row.project}</div></div>)}</div></div></Card>;
}

export function ProjectFinancialSummary({ rows }: { rows: ProjectAnalytics[] }) {
  const totals = rows.reduce((result, row) => ({ consumers: result.consumers + row.consumers, units: result.units + row.units, materialLossPaid: result.materialLossPaid + row.materialLossPaid, contractValue: result.contractValue + row.contractValue }), { consumers: 0, units: 0, materialLossPaid: 0, contractValue: 0 });
  return <Card className="overflow-x-auto"><div className="border-b border-hairline p-6"><h2 className="text-lg font-medium text-ink">Project financial summary</h2><p className="mt-1 text-sm text-muted">Material paid includes numeric Refund values only. Contract value is summed across all units.</p></div><table className="min-w-[780px] w-full text-left text-sm"><thead className="bg-surface-soft font-mono text-[11px] tracking-[0.5px] text-muted uppercase"><tr><th className="px-6 py-3">Project location</th><th className="px-4 py-3 text-right">Consumers</th><th className="px-4 py-3 text-right">Units</th><th className="px-4 py-3 text-right">Material paid</th><th className="px-6 py-3 text-right">Nilai Kontrak Unit</th></tr></thead><tbody className="divide-y divide-hairline-soft">{rows.map((row) => <tr key={row.project}><td className="px-6 py-4 font-medium text-ink">{row.project}</td><td className="px-4 py-4 text-right font-mono text-ink">{row.consumers}</td><td className="px-4 py-4 text-right font-mono text-ink">{row.units}</td><td className="px-4 py-4 text-right font-mono text-ink">{rupiah.format(row.materialLossPaid)}</td><td className="px-6 py-4 text-right font-mono text-ink">{rupiah.format(row.contractValue)}</td></tr>)}</tbody><tfoot className="border-t-2 border-ink bg-surface-soft font-medium text-ink"><tr><td className="px-6 py-4">Total</td><td className="px-4 py-4 text-right font-mono">{totals.consumers}</td><td className="px-4 py-4 text-right font-mono">{totals.units}</td><td className="px-4 py-4 text-right font-mono">{rupiah.format(totals.materialLossPaid)}</td><td className="px-6 py-4 text-right font-mono">{rupiah.format(totals.contractValue)}</td></tr></tfoot></table></Card>;
}

function VerticalSegment({ value, max, color }: { value: number; max: number; color: string }) { return value ? <div className={color} style={{ height: `${(value / max) * 100}%` }} /> : null; }
function Legend({ color, label }: { color: string; label: string }) { return <span className="inline-flex items-center gap-1.5"><span className={`h-2.5 w-2.5 rounded-sm ${color}`} />{label}</span>; }
